version: '3.1'

services:
  mssql:
    build:
      context: .
      dockerfile: ./data/Dockerfile.data
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: Y
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/entrypoint.sh"]
    networks:
      - web

  backend:
    networks:
      - web
    build:
      context: .
      dockerfile: ../backend/Dockerfile
    container_name: express-backend
    ports:
      - 3000:3000
    environment:
      DB_HOST: mssql
      DB_USER: sa
      DB_PASS: YourStrong!Passw0rd
      DB_NAME: db1
      DB_PORT: 1433
    depends_on:
      - mssql
networks:
  web:
    driver: bridge